# Generated by Django 3.0 on 2021-07-19 04:03

from django.db import migrations, models
import django.utils.timezone
import src.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', src.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
